### ISSUE TITLE
App shared resources maintains old app logo

### ISSUE THREAD

**Issue by esreli** [Esri/dynamic-situational-awareness-qt#314]
The [old app logo](https://github.com/Esri/dynamic-situational-awareness-qt/blob/master/Shared/Resources/icons/xhdpi/applogo.png) is maintained within the shared resources.

If the app is dependent on this logo, we will need to point to the new logo. If this logo is not referenced, can it be removed?

**Comment by kathleen1** [comment]
Hi @esreli, I saw in one of the Runtime Group meetings that icon (including color) will be changing. I'll be checking with Rex, when he returns, as those changes may not happen until the 100.8 April release. But you can check with him, as far as the updated ones (used at 100.7), if that'd make sense.

**Comment by esreli** [comment]
Hi @kathleen1, I look forward to seeing the final result. Exciting stuff!

Like Runtime is currently, Open Source Apps also had our app icon redesigned. That design is delivered and installed in all of our apps. What i'm seeing here is the old _Open Source Apps_ icon (note the black ribbon across the bottom that reads "example").

As I understand it, Qt DSA has also swapped app icons in favor of the new design. What i'm pointing to here is (what appears to be) a legacy unused file.
