### ISSUE TITLE
Qt build error solved | Modify the installation path (without spaces) to solve this problem 

### ISSUE THREAD

**Issue by pengguanjun** [Esri/dynamic-situational-awareness-qt#357]
Build Environment
OS: Win 10 Desktop
QT-Creater Versoin: 4.14.2
QT-Version: 5.15.2 mingw 64 Bit

Issue: Unable to build project

Spaces are replaced by / 
for example:

../../../../Program\ Files\ (x86)/ArcGIS\ SDKs/Qt100.10/sdk/include/LegendInfoListModel.h \
C:\Program Files (x86)\ArcGIS SDKs\Qt100.10\sdk\include

Modify the installation path (without spaces) to solve this problem 
New path is good to build.Such as:
C:\arcgis\Qt100.10\sdk\include

more error details:
windres -i ..\..\dynamic-situational-awareness-qt\Handheld\Win\Resources.rc -o release\Resources_res.o --include-dir=./../../dynamic-situational-awareness-qt/Handheld/Win -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DCPP_ARCGISRUNTIME_TOOLKIT -DARCGIS_RUNTIME_IMPORT_PATH="C:/Program Files (x86)/ArcGIS SDKs/Qt100.10/sdk/windows/x64/qml" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_SENSORS_LIB -DQT_XML_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN
**gcc: error: Files\: No such file or directory**
gcc: error: \(x86\)/ArcGIS\: No such file or directory
gcc: error: SDKs/Qt100.10/sdk/windows/x64/qml: No such file or directory
windres: preprocessing failed.

![图片](https://user-images.githubusercontent.com/29192658/116762575-6a722000-aa4d-11eb-9eb9-88bd7544c01a.png)

**Comment by JamesMBallard** [comment]
Hi @pengguanjun. Thanks for posting this. We don't support the MinGW Qt Kit on Windows with the ArcGIS Runtime SDK for Qt. The Visual Studio 2019 kit is required. You may run into more problems if you proceed with the MinGW kit for Windows.

Here are our latest requirements: https://developers.arcgis.com/qt/reference/system-requirements/#developing-apps-on-windows

**Comment by anmacdonald** [comment]
Closing as we do not support MinGW.
