### ISSUE TITLE
error: Ole32.lib: No such file or directory

### ISSUE THREAD

**Issue by pengguanjun** [Esri/dynamic-situational-awareness-qt#358]
LIBS +=     Ole32.lib
adjust to:
LIBS +=     $$PWD/Ole32.lib
![图片](https://user-images.githubusercontent.com/29192658/116763923-d5bdf100-aa51-11eb-8bfd-114afbfad3c2.png)
I try my all eight Ole32.lib files, all error, could you help me?

**Comment by JamesMBallard** [comment]
Hi @pengguanjun. You'll need to use the Visual Studio 2019 kit to build on Windows. We don't support the MinGW kit, which I assume you're using based on https://github.com/Esri/dynamic-situational-awareness-qt/issues/357.

Please reference: https://developers.arcgis.com/qt/reference/system-requirements/#developing-apps-on-windows

**Comment by pengguanjun** [comment]
Thx, I only have vs2017 now, I will try it first.

**Comment by pengguanjun** [comment]
You are right. By using the Visual Studio 2019 kit with qt5.15.2 to build on Windows, running is ok.
But, I get a new problem.
**qrc:/qml/main.qml:25:1: module "Esri.ArcGISRuntime.Toolkit" version 100.10 is not installed **

![图片](https://user-images.githubusercontent.com/29192658/116954040-69e1bf80-acc1-11eb-9812-44c1abd4f12c.png)

Maybe, I ignore something.

Handheld and Vehicle run result:
![图片](https://user-images.githubusercontent.com/29192658/116954098-9c8bb800-acc1-11eb-9161-09a833dd624d.png)

MessageSimulator runs result:
![图片](https://user-images.githubusercontent.com/29192658/116954151-c0e79480-acc1-11eb-9c0c-a305ac386ba7.png)

**Comment by anmacdonald** [comment]
Hi there, my solution to your other issue should fix your toolkit problem:
https://github.com/Esri/dynamic-situational-awareness-qt/issues/359

**Comment by anmacdonald** [comment]
Marking this issue as now fixed.
