### ISSUE TITLE
Test out MANAGE_EXTERNAL_STORAGE for use in DSA

### ISSUE THREAD

**Issue by ldanzinger** [Esri/dynamic-situational-awareness-qt#372]
Tanner has been using the permission `<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>` to easily sideload data outside of Android Studio. We should test out if that is an option to simplify the workflow for DSA https://developer.android.com/training/data-storage/manage-all-files

cc @dtedder

**Comment by kerryrobinson** [comment]
It looks like this method will not work for our purposes.  Decision was made to keep the data in the sandbox, but in a folder named "DSA".  Closing this issue.
