### ISSUE TITLE
Duplicate set of DE Layers in the Overlays panel

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/dynamic-situational-awareness-qt#373]
With the update to Dynamic Entities, the DE Layers now show up in the Overlays panel.  In the longer term we need to re-work the UI or figure out how to instead hook them into the Feeds panel (as it worked prior to the update to DE). 

For now though there is an issue where there is a duplciation of those DE layers in the Overlays panel. I see this in the Android version of the app:
<img src="https://github.com/Esri/dynamic-situational-awareness-qt/assets/3383476/2310a71f-f1f1-4fcd-869a-2ce7702dc2c4" width=200/>
and I did see it in the Windows version but I'm unable to reproduce that at the moment. 

Expected behavior for now is to only have one set of feeds display in the Overlays tab.

**Comment by dtedder** [comment]
@kerryrobinson

Addressed by this commit:

https://github.com/Esri/dynamic-situational-awareness-qt/pull/371/commits/c37c0f1fd19492c55e3dcc6ea424997462d2da4e

**Comment by kerryrobinson** [comment]
Confirming this is fixed in the latest branch. Closing.
