### ISSUE TITLE
Viewshed not working when attached to a Dynamic Entity

### ISSUE THREAD

**Issue by dtedder** [Esri/dynamic-situational-awareness-qt#379]
Viewshed is not working correctly for both ways you can attach it to a Dynamic Entity:

1- Long-press on a DE (i.e. from friendly land tracks) and choose Viewshed. When this is done, the Viewshed is placed on the map where the mouse clicked, instead of on the DE as it moves. 
2- Choose "Map Element" from the Viewshed tool. Nothing happens when you click on or near a DE. 

_Note, this might work correctly for features from layers, just not DEs_

**Comment by kerryrobinson** [comment]
Use case 1 (long-press and choose Viewshed) never worked (should add a new issue for this to be tackled at some point).

Use case 2 (start with viewshed tool and then click on DE) should be fixed.

**Comment by kerryrobinson** [comment]
Use case 2 is working now. 👍
