### ISSUE TITLE
Use formatted names for Message Feeds

### ISSUE THREAD

**Issue by dtedder** [Esri/dynamic-situational-awareness-qt#381]
When creating a new condition, the drop down list of feeds uses the short names for the feeds instead of the formatted version from the config file. 
| Previous Version | Latest Version | 
| --- | --- | 
| ![Image](https://github.com/user-attachments/assets/422edb65-7241-4205-a1b2-e16ab9046ddf) | ![Image](https://github.com/user-attachments/assets/9f1a5ad0-475b-4150-b981-4a9114ea4d9e) |

**Comment by kerryrobinson** [comment]
Looks good!  👍
