### ISSUE TITLE
App crashes when turning off an alert in the Alerts list.

### ISSUE THREAD

**Issue by dtedder** [Esri/dynamic-situational-awareness-qt#389]
Similar to the issue where the app crashes when I remove a layer from the overlays list, i wasn't able to reproduce this after the first time I tried it.

**Comment by dtedder** [comment]
@kerryrobinson 
Similar to issue #388 , I've not been able to reproduce on my end. Is there any more context that might be relevant to get this to repro? I have attempted to most options from the alerts panel itself as well as the individual alert that's actively happening (highlight, dismiss, zoom to). This could be no longer reproducible following some of the recent updates from #387 #371 .

**Comment by kerryrobinson** [comment]
I can't replicate this as well.
